---
candlepin_git_pull: True

candlepin_user_home:  /home/jenkins

candlepin_git_repo: https://github.com/candlepin/candlepin.git
candlepin_checkout: /home/jenkins/candlepin
candlepin_branch: master

# feel free to change arguments but keep in mind
# the test is meant to work with mysql, so requires -m
candlepin_deploy_args: "-maH"

caracalla_git_repo: https://github.com/candlepin/caracalla.git
caracalla_checkout: /home/jenkins/caracalla
caracalla_branch: master

# The test to run, other tests defined in jmeter_test_details
# will be skipped
jmeter_tests:
# - loop-over-apis
 - candlepin-throughput

# The details about all tests, only the ones in jmeter_test will run.
jmeter_test_details:
  loop-over-apis:
    folder: Candlepin-API
    test_name: CandlepinAPI.jmx
    baseline: baseline.dict
    expected: expected.dict
    property_file: /home/jenkins/Candlepin-API/CandlepinAPI.prop
    result_file: results-CandlepinAPI.jtl
  ImportExport:
    folder: ImportExportManifest
    test_name: ImportExportManifest.jmx
    property_file: /home/jenkins/ImportExportManifest.prop
    result_file: results-importexport.jtl
    baseline: baseline.dict
    expected: expected.dict
  candlepin-throughput:
    folder: candlepin-throughput
    test_name: candlepin-throughput.jmx
    property_file: /home/jenkins/candlepin-throughput/candlepin-throughput.prop
    result_file: results-throughput.jtl
    baseline: baseline.dict
    expected: expected.dict

candlepin_throughput_properties:
 - DURATION_SECONDS=3600
 - SAMPLES_PER_MINUTE=6900
